# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VMv7VGwOwhj6fIhCnE7TYrJmiWhg_4Sn
"""

# Nhập số lượng phần tử
N = int(input("Nhập số lượng số nguyên N: "))

# Khởi tạo các biến thống kê
tong = 0
dem_chan = 0

# Nhập số đầu tiên để khởi tạo max và min
x = int(input("Nhập số thứ 1: "))
max_val = x
min_val = x
tong += x
if x % 2 == 0:
    dem_chan += 1

# Vòng lặp duy nhất cho các số còn lại
for i in range(2, N + 1):
    x = int(input(f"Nhập số thứ {i}: "))

    # Cập nhật max, min
    if x > max_val:
        max_val = x
    if x < min_val:
        min_val = x

    # Cập nhật tổng
    tong += x

    # Đếm số chẵn
    if x % 2 == 0:
        dem_chan += 1

# Tính trung bình
trung_binh = tong / N

# In kết quả
print("Số lớn nhất:", max_val)
print("Số nhỏ nhất:", min_val)
print("Giá trị trung bình:", trung_binh)
print("Số lượng số chẵn:", dem_chan)